#!/bin/sh

TOP_LEVEL=$(git rev-parse --show-toplevel)
BUILD=${TOP_LEVEL}/build
TEST=${BUILD}/src/aeten/core/algebra
$(${TOP_LEVEL}/aeten-cli/aeten-cli.sh import all)

for lang in c cpp; do
	check -m "Test ${lang} algebra/base" test "'$(${TEST}/base.${lang}.o -i 8 -o 16 173 -v)'" = "'ibase=8, obase=16, value=173
173(base 8) = 1*8^2 + 7*8^1 + 3*8^0 = 123(base 10)
123/16 = 7 remains 11(b)
7/16 = 0 remains 7(7)
173(base 8) = 7b(base 16)
7b'"
done
